### ISSUE TITLE
Error on opening graph with virtual signals

### ISSUE THREAD

**Issue by yump** [KirkMcDonald/factorio-timeseries#1]
The plotter works great with signals corresponding to items, but if I connect it to a circuit carrying virtual signals ("A", red, etc.), opening the UI triggers an error that looks like this:

>Error while running event timeseries::on_gui_opened (ID 83)
>Unknown sprite "virtual/signal-red"

**Comment by KirkMcDonald** [comment]
Fixed in f0a1ca1d080881ce0a5b3d73321c214d341fbfdc.
